apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /packages
  name: challenge-delta-ingress
  namespace: challenge-delta
spec:
  rules:
  - host: challenge-delta.info
    http:
      paths:
      - backend:
          serviceName: nodeapp
          servicePort: 8888
        path: /