version: "3.3"
services:  
  mysql:
    image: mysql:5.7.28
    container_name: hurb_mysql
    working_dir: /application
    volumes:
      - ../db/mysql:/var/lib/mysql
      - ../db/schema:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: 'packages'
      MYSQL_ROOT_PASSWORD: 'hurb_root'
      MYSQL_USER: 'user_packages'
      MYSQL_PASSWORD: 'passwords'
    ports:
      - "3306:3306"
  
  nodejs:
    build:
      context: node/.
      dockerfile: Dockerfile
    image: hurb_node
    container_name: hurb_node
    restart: always
    environment:
      WAIT_HOSTS: mysql:3306
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: hurb_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error:/usr/share/nginx/html/error
    links:
      - nodejs
    depends_on:
      - nodejs
